apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-adapter
  labels:
    app: grafana-adapter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-adapter
  template:
    metadata:
      annotations:
        cni.daocloud.io/subnet: 192.168.0.0/16
      labels:
        app: grafana-adapter
    spec:
      hostNetwork: true
      containers:
      - name: grafana-adapter
        image: grafana-adapter:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 25Mi
        env:
        - name: CONFIG_PATH
          value: "/adapter"
        - name: GRAFANA_IP
          value: "10.100.194.70"
        - name: PROMETHEUS_IP
          value: "10.101.3.181"
        - name: ADMIN_NAME
          value: "admin"
        - name: ADMIN_PASSWORD
          value: "admin"

