apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-controller
  labels:
    app: grafana-controller
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-controller
  template:
    metadata:
      annotations:
        cni.daocloud.io/subnet: 192.168.0.0/16
      labels:
        app: grafana-controller
    spec:
      hostNetwork: true
      containers:
      - name: grafana-controller
        image: grafana-controller:0.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 25Mi
        env:
        - name: CONFIG_PATH
          value: "/controller"
        - name: GRAFANA_IP
          value: "10.103.75.37"
        - name: PROMETHEUS_IP
          value: "10.106.107.252"
        - name: ADMIN_NAME
          valueFrom:
            secretKeyRef:
              name: grafana-admin
              key: username
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-admin
              key: password
